---
- name: Install and start Apache
  hosts: all
  become: yes 
  tasks:
    - name: Ensure Apache is installed
      apt: name=apache2  state=present update_cache=yes

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create index.html file
      copy:
        content: "<h1>Hello World from {{ ansible_hostname }}</h1>"
        dest: /var/www/html/index.html



